#!/usr/bin/env python3
"""
Adversarial Stress Test Suite for Milestone 1: Visual Identity & SVG Assets
Ecosystem: DuongNAD/DuongNAD (Living Systems / Nordic Twilight Nature Aesthetic)

Author: teamwork_preview_challenger_m1_1 (Empirical Challenger)
Target Assets:
- assets/header.svg
- assets/footer.svg
- assets/github-contribution-grid-snake-dark.svg
- assets/github-contribution-grid-snake.svg
- scripts/generate_nature_banner.py

Test Dimensions:
1. Malformed / Corrupted SVG Injection Resilience & Security Sanitization
2. Viewport Resizing & Extreme Aspect Ratio Stress Harness (320px mobile to 5120px super-ultrawide)
3. XML Namespace, SAX Parsing & UTF-8 Character Encoding (Diacritics, Entities, Normalization)
4. CSS Specificity, Variable Inheritance & Cascade Isolation
5. Deep Vector Coordinate Bounding & Color Token Hygiene
"""

import io
import math
import os
import re
import sys
import unicodedata
import unittest
import xml.dom.minidom
import xml.etree.ElementTree as ET
import xml.sax
import xml.sax.handler
from pathlib import Path
from typing import Dict, List, Set, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent

# Living Systems Emerald/Teal Approved Palette
APPROVED_HEXES = {
    "10B981", "059669", "047857", "064E3B", "34D399", "6EE7B7", "A7F3D0", "D1FAE5",
    "0D9488", "14B8A6", "0F766E", "115E59", "134E4A", "2DD4BF", "5EEAD4", "99F6E4",
    "134236", "0B241E", "05120F", "04120E", "081E1A", "143E37", "1B4D43", "091F24",
    "0F342D", "14463C", "1B4D43", "0D2B25", "050D14", "1D4E3F", "020806", "03100C",
    "03110E", "020A08", "061813", "082019", "06181D", "0B2E28", "12443A", "185246",
    "065F46", "03080D", "184A3F", "123B32", "0C2923", "0C2721", "061A15", "164E3F",
    "FEF9C3", "FDE047", "ECFDF5", "F0FDF4", "FFFFFF",
    "0F172A", "1E293B", "334155", "0B1220", "020617",
}

FORBIDDEN_CYAN_BLUE_HEXES = {
    "38BDF8", "1E3A8A", "2563EB", "3B82F6", "60A5FA", "00FFFF", "FF00FF"
}


# ============================================================================
# 1. CORRUPTED / MALFORMED SVG INJECTION RESILIENCE & SECURITY AUDIT
# ============================================================================

class TestSvgSecurityAndInjectionResilience(unittest.TestCase):
    """
    Stress-tests the assets against malicious payloads, injection attacks,
    broken internal references, and unclosed tags.
    """

    def setUp(self):
        self.header_path = REPO_ROOT / "assets" / "header.svg"
        self.footer_path = REPO_ROOT / "assets" / "footer.svg"
        self.snake_dark_path = REPO_ROOT / "assets" / "github-contribution-grid-snake-dark.svg"
        self.targets = [self.header_path, self.footer_path, self.snake_dark_path]

    def test_asset_security_sanitization(self):
        """Verify zero script, zero event handlers, zero foreignObjects, and zero external resource fetches."""
        dangerous_patterns = [
            (r"<script[\s>]", "Embedded <script> tag"),
            (r"\bon\w+\s*=", "Inline event handler (e.g. onload, onclick)"),
            (r"javascript:", "Javascript pseudo-protocol"),
            (r"<foreignObject[\s>]", "<foreignObject> injection vulnerability"),
            (r"@import\s+", "CSS @import external stylesheet"),
            (r"<link[\s>]", "HTML/XML <link> reference"),
            (r"(?:href|src|xlink:href)\s*=\s*['\"]https?://", "External HTTP/HTTPS link resource fetch"),
            (r"url\s*\(\s*['\"]?https?://", "External CSS url() network resource fetch"),
            (r"data:text/html", "Data URI HTML payload"),
        ]

        for target in self.targets:
            self.assertTrue(target.exists(), f"Target file missing: {target}")
            content = target.read_text(encoding="utf-8")
            
            # Allow github generator link only inside <desc> of snake if generated by platane/snk
            scrubbed_content = content
            if "github-contribution-grid-snake" in target.name:
                scrubbed_content = re.sub(r"<desc>.*?</desc>", "", content, flags=re.DOTALL)

            for pattern, desc in dangerous_patterns:
                match = re.search(pattern, scrubbed_content, re.IGNORECASE)
                self.assertIsNone(
                    match,
                    f"Security vulnerability detected in {target.name}: {desc} (match: '{match.group(0) if match else ''}')"
                )

    def test_internal_gradient_and_clip_reference_integrity(self):
        """
        Verify all url(#id) references in fill, stroke, clip-path resolve to valid declared IDs in <defs>.
        Broken references cause rendering corruption or solid black artifacts on SVG renderers.
        """
        for target in [self.header_path, self.footer_path]:
            content = target.read_text(encoding="utf-8")
            tree = ET.parse(target)
            root = tree.getroot()

            # Collect all defined IDs
            defined_ids = set()
            for elem in root.iter():
                elem_id = elem.get("id")
                if elem_id:
                    defined_ids.add(elem_id)

            # Find all url(#id) references in XML
            url_refs = set(re.findall(r'url\(#([a-zA-Z0-9_\-]+)\)', content))
            
            self.assertGreater(len(url_refs), 0, f"{target.name} should define and use gradient URLs")
            missing_ids = url_refs - defined_ids
            self.assertEqual(
                len(missing_ids), 0,
                f"{target.name} contains dangling url(#id) references with no matching element: {missing_ids}"
            )

    def test_parser_fuzzing_and_corruption_resilience(self):
        """
        Construct adversarial corruptions of the SVG assets (truncation, tag tampering,
        malformed entities, null bytes) and verify strict parser failure detection.
        """
        sample_svg = self.header_path.read_text(encoding="utf-8")

        corrupted_mutations = [
            ("Truncated mid-tag", sample_svg[:len(sample_svg)//2]),
            ("Unclosed style tag", sample_svg.replace("</style>", "")),
            ("Unescaped raw ampersand in text", sample_svg.replace("NGUYỄN ANH DƯƠNG", "Duong & Friends")),
            ("Malformed entity", sample_svg.replace("&amp;", "&unknownEntity;")),
            ("Embedded null byte", sample_svg[:500] + "\x00" + sample_svg[500:]),
            ("Mismatched closing tag", sample_svg.replace("</defs>", "</div>")),
            ("Unquoted attribute value", sample_svg.replace('viewBox="0 0 1200 260"', 'viewBox=0 0 1200 260')),
            ("Broken CDATA block", sample_svg.replace("<defs>", "<defs><![CDATA[unclosed cdata")),
        ]

        for mutation_name, mutated_content in corrupted_mutations:
            with self.assertRaises(ET.ParseError, msg=f"Parser failed to reject corrupted payload: {mutation_name}"):
                ET.fromstring(mutated_content)

    def test_xml_entity_expansion_bomb_mitigation(self):
        """Verify XML External Entity (XXE) and billion laughs bombs are rejected or not processed."""
        xxe_payload = """<?xml version="1.0"?>
        <!DOCTYPE lolz [
         <!ENTITY lol "lol">
         <!ELEMENT lolz (#PCDATA)>
         <!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
         <!ENTITY lol2 "&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;">
        ]>
        <svg xmlns="http://www.w3.org/2000/svg">&lol2;</svg>"""

        # Ensure standard parsing fails or handles safely without crash
        try:
            tree = ET.fromstring(xxe_payload)
            # If parsed, ensure entity is not expanded infinitely
            self.assertTrue(True)
        except ET.ParseError:
            # Expected behavior on secure/standard parsers
            self.assertTrue(True)


# ============================================================================
# 2. VIEWPORT RESIZING & EXTREME ASPECT RATIO STRESS HARNESS
# ============================================================================

class TestViewportResizingAndAspectRatios(unittest.TestCase):
    """
    Simulates viewport projections from 320px mobile to 5120px super-ultrawide.
    Verifies viewBox geometry, scaling invariants, and layout containment.
    """

    def setUp(self):
        self.header_path = REPO_ROOT / "assets" / "header.svg"
        self.footer_path = REPO_ROOT / "assets" / "footer.svg"
        self.snake_dark_path = REPO_ROOT / "assets" / "github-contribution-grid-snake-dark.svg"

    def _parse_viewbox(self, path: Path) -> Tuple[float, float, float, float]:
        root = ET.parse(path).getroot()
        vb_str = root.get("viewBox", "").strip()
        parts = [float(p) for p in re.split(r'[\s,]+', vb_str) if p]
        self.assertEqual(len(parts), 4, f"viewBox in {path.name} must have 4 numeric components: '{vb_str}'")
        return tuple(parts)

    def test_viewbox_specifications(self):
        """Check exact viewBox contracts and aspect ratio invariants."""
        # Header contract: 0 0 1200 260 (Aspect ~4.615)
        hx, hy, hw, hh = self._parse_viewbox(self.header_path)
        self.assertEqual((hx, hy), (0.0, 0.0))
        self.assertEqual((hw, hh), (1200.0, 260.0))
        self.assertAlmostEqual(hw / hh, 1200 / 260, places=4)

        # Footer contract: 0 0 1200 90 (Aspect ~13.333)
        fx, fy, fw, fh = self._parse_viewbox(self.footer_path)
        self.assertEqual((fx, fy), (0.0, 0.0))
        self.assertEqual((fw, fh), (1200.0, 90.0))
        self.assertAlmostEqual(fw / fh, 1200 / 90, places=4)

        # Snake dark contract: -16 -32 880 192
        sx, sy, sw, sh = self._parse_viewbox(self.snake_dark_path)
        self.assertEqual((sx, sy), (-16.0, -32.0))
        self.assertEqual((sw, sh), (880.0, 192.0))

    def test_multi_resolution_viewport_projection(self):
        """
        Simulate rendering across 13 diverse viewport resolutions.
        Verify aspect-ratio scaling factors and translation coordinates under 'meet' scaling.
        """
        test_viewports = [
            (320, 50, "Mobile Slim Banner"),
            (320, 240, "Legacy Mobile Screen"),
            (375, 667, "iPhone SE Viewport"),
            (412, 915, "Modern Android Flagship"),
            (768, 1024, "iPad Portrait"),
            (1024, 768, "iPad Landscape"),
            (1200, 260, "Header Design Native"),
            (1200, 90, "Footer Design Native"),
            (1920, 1080, "Full HD Desktop"),
            (2560, 1440, "2K Desktop Monitor"),
            (3440, 1440, "21:9 Ultrawide"),
            (3840, 2160, "4K UHD Display"),
            (5120, 1440, "32:9 Super Ultrawide"),
        ]

        for target_path in [self.header_path, self.footer_path, self.snake_dark_path]:
            vx, vy, vw, vh = self._parse_viewbox(target_path)
            for vp_w, vp_h, vp_label in test_viewports:
                # Under preserveAspectRatio='xMidYMid meet'
                scale = min(vp_w / vw, vp_h / vh)
                rendered_w = vw * scale
                rendered_h = vh * scale
                offset_x = (vp_w - rendered_w) / 2.0
                offset_y = (vp_h - rendered_h) / 2.0

                self.assertGreater(scale, 0, f"Scale must be positive for {target_path.name} in {vp_label}")
                self.assertLessEqual(rendered_w, vp_w + 1e-4)
                self.assertLessEqual(rendered_h, vp_h + 1e-4)
                self.assertGreaterEqual(offset_x, -1e-4)
                self.assertGreaterEqual(offset_y, -1e-4)

    def test_header_visual_elements_clearance_and_containment(self):
        """
        Stress-test spatial layout in header.svg:
        - Stag silhouette must NOT collide with the center typography card.
        - Text elements must remain well inside the 610x132 glassmorphic card.
        """
        tree = ET.parse(self.header_path)
        root = tree.getroot()

        # Center typography card boundary: x=295, y=74, width=610, height=132 -> [295..905], [74..206]
        card_x_min, card_x_max = 295.0, 295.0 + 610.0
        card_y_min, card_y_max = 74.0, 74.0 + 132.0

        # Stag transform: translate(130, 112) scale(0.85)
        # Bounding box of STAG_PATH in local coords is approx: x in [0.1..95.9], y in [0.0..114.9]
        stag_local_x_max = 95.9
        stag_local_y_max = 114.9
        stag_world_x_max = 130.0 + 0.85 * stag_local_x_max  # ~211.5
        stag_world_y_max = 112.0 + 0.85 * stag_local_y_max  # ~209.7

        # Stag must be cleanly to the left of the center card
        stag_card_clearance = card_x_min - stag_world_x_max
        self.assertGreater(
            stag_card_clearance, 40.0,
            f"Stag silhouette too close to center text card! Clearance: {stag_card_clearance}px"
        )

        # Center typography text anchor is x=600 (center of 1200)
        # Check text lines in header
        texts = root.findall(".//{http://www.w3.org/2000/svg}text")
        self.assertGreaterEqual(len(texts), 4, "Header must contain at least 4 text elements")
        for t in texts:
            tx = float(t.get("x", "0"))
            ty = float(t.get("y", "0"))
            self.assertEqual(tx, 600.0, f"Header text '{t.text}' must be centered at x=600")
            self.assertGreaterEqual(ty, card_y_min, f"Text '{t.text}' y={ty} above card top {card_y_min}")
            self.assertLessEqual(ty, card_y_max, f"Text '{t.text}' y={ty} below card bottom {card_y_max}")

    def test_footer_responsive_attributes(self):
        """Verify footer.svg contains responsive attributes (width='100%', height='100%')."""
        root = ET.parse(self.footer_path).getroot()
        self.assertEqual(root.get("width"), "100%", "Footer width must be '100%'")
        self.assertEqual(root.get("height"), "100%", "Footer height must be '100%'")
        self.assertIn("meet", root.get("preserveAspectRatio", ""), "Footer must specify meet aspect ratio")


# ============================================================================
# 3. XML NAMESPACE, SAX PARSING & CHARACTER ENCODING CHECKS
# ============================================================================

class TestXmlNamespaceAndCharacterEncoding(unittest.TestCase):
    """
    Validates XML namespace declarations, multi-parser consensus (DOM, SAX, ET),
    and character encoding integrity (UTF-8, NFC diacritics, XML entity escaping).
    """

    def setUp(self):
        self.header_path = REPO_ROOT / "assets" / "header.svg"
        self.footer_path = REPO_ROOT / "assets" / "footer.svg"
        self.snake_dark_path = REPO_ROOT / "assets" / "github-contribution-grid-snake-dark.svg"
        self.targets = [self.header_path, self.footer_path, self.snake_dark_path]

    def test_multi_parser_consensus(self):
        """
        Verify all target SVGs parse identically across 3 independent XML parsers:
        1. xml.etree.ElementTree (C-accelerated tree builder)
        2. xml.dom.minidom (W3C DOM Level 2 parser)
        3. xml.sax (Streaming event parser with namespace validation)
        """
        class StrictSaxHandler(xml.sax.handler.ContentHandler):
            def __init__(self):
                super().__init__()
                self.element_count = 0
                self.has_svg_root = False

            def startElementNS(self, name, qname, attrs):
                uri, localname = name
                if self.element_count == 0:
                    if uri == "http://www.w3.org/2000/svg" and localname == "svg":
                        self.has_svg_root = True
                self.element_count += 1

        for target in self.targets:
            # 1. ElementTree
            et_root = ET.parse(target).getroot()
            self.assertEqual(et_root.tag, "{http://www.w3.org/2000/svg}svg")

            # 2. Minidom
            dom = xml.dom.minidom.parse(str(target))
            self.assertEqual(dom.documentElement.tagName, "svg")
            self.assertEqual(dom.documentElement.getAttribute("xmlns"), "http://www.w3.org/2000/svg")

            # 3. SAX with Namespace feature
            parser = xml.sax.make_parser()
            parser.setFeature(xml.sax.handler.feature_namespaces, True)
            handler = StrictSaxHandler()
            parser.setContentHandler(handler)
            with open(target, "rb") as f:
                parser.parse(f)
            self.assertTrue(handler.has_svg_root, f"{target.name} SAX parser failed to find SVG root in SVG namespace")
            self.assertGreater(handler.element_count, 1, f"{target.name} element count too low")

    def test_utf8_clean_bytes_and_diacritics_normalization(self):
        """
        Verify strict UTF-8 decoding without replacement characters or BOM.
        Verify Unicode NFC canonical decomposition/composition on Vietnamese diacritics.
        """
        for target in self.targets:
            raw = target.read_bytes()

            # Disallow UTF-8 BOM (\xef\xbb\xbf) which can break some strict SVG processors
            self.assertFalse(raw.startswith(b"\xef\xbb\xbf"), f"{target.name} has unexpected UTF-8 BOM header")

            # Decode strictly as UTF-8
            text = raw.decode("utf-8")
            self.assertNotIn("\ufffd", text, f"{target.name} contains Unicode REPLACEMENT CHARACTER (U+FFFD)")

            # Check normalization
            nfc_text = unicodedata.normalize("NFC", text)
            self.assertEqual(text, nfc_text, f"{target.name} text should be canonical Unicode NFC form")

    def test_vietnamese_diacritics_and_special_symbols(self):
        """Verify candidate's name diacritics ('NGUYỄN ANH DƯƠNG') and symbols are preserved."""
        header_text = self.header_path.read_text(encoding="utf-8")
        self.assertIn("NGUYỄN ANH DƯƠNG", header_text, "Candidate name with diacritics missing in header.svg")
        self.assertIn("✦", header_text, "Star symbol '✦' missing in header badge")
        self.assertIn("·", header_text, "Middle dot symbol '·' missing in header meta")

        # Explicit codepoint check for Vietnamese diacritics
        name = "NGUYỄN ANH DƯƠNG"
        self.assertIn("\u1ec4", name, "Ễ (U+1EC4) must be present")
        self.assertIn("\u01af", name, "Ư (U+01AF) must be present")
        self.assertIn("\u01a0", name, "Ơ (U+01A0) must be present")

        footer_text = self.footer_path.read_text(encoding="utf-8")
        self.assertIn("NGUYEN ANH DUONG (DuongNAD)", footer_text, "Signature missing in footer.svg")
        self.assertIn("·", footer_text, "Middle dot symbol '·' missing in footer.svg")

    def test_xml_entity_escaping_soundness(self):
        """
        Verify all literal ampersands in markup, attributes, and text nodes are properly escaped as &amp;.
        Ignores XML comments where ampersands are valid non-markup characters.
        """
        for target in self.targets:
            content = target.read_text(encoding="utf-8")
            # Strip comments first
            no_comments = re.sub(r'<!--.*?-->', '', content, flags=re.DOTALL)
            raw_amp_pattern = r'&(?!(amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);)'
            raw_amps = re.findall(raw_amp_pattern, no_comments)
            self.assertEqual(
                len(raw_amps), 0,
                f"Found {len(raw_amps)} unescaped ampersand(s) outside comments in {target.name}"
            )


# ============================================================================
# 4. CSS SPECIFICITY, VARIABLE INHERITANCE & PALETTE COMPLIANCE
# ============================================================================

class TestCssSpecificityAndVariableInheritance(unittest.TestCase):
    """
    Stress-tests CSS rule definitions, variable binding, keyframe animations,
    and Living Systems emerald/teal palette harmony.
    """

    def setUp(self):
        self.header_path = REPO_ROOT / "assets" / "header.svg"
        self.footer_path = REPO_ROOT / "assets" / "footer.svg"
        self.snake_dark_path = REPO_ROOT / "assets" / "github-contribution-grid-snake-dark.svg"

    def test_snake_dark_css_variable_integrity(self):
        """
        Verify CSS variables in github-contribution-grid-snake-dark.svg:
        - All variables referenced via var(--name) must be explicitly defined in :root.
        - Exactly 0 undefined variable fallbacks.
        - Zero cyber-blue/neon hex literals in the stylesheet.
        """
        content = self.snake_dark_path.read_text(encoding="utf-8")
        style_match = re.search(r"<style>(.*?)</style>", content, re.DOTALL)
        self.assertIsNotNone(style_match, "Style tag missing in snake dark asset")
        css_text = style_match.group(1)

        # 1. Extract :root block
        root_match = re.search(r':root\s*\{([^}]+)\}', css_text)
        self.assertIsNotNone(root_match, ":root block missing in snake dark CSS")
        root_body = root_match.group(1)

        # Parse declared variables
        declared_vars = {}
        for decl in root_body.split(";"):
            decl = decl.strip()
            if decl and ":" in decl:
                var_name, var_val = decl.split(":", 1)
                declared_vars[var_name.strip()] = var_val.strip()

        # Check required snake variables
        required_vars = ["--cb", "--cs", "--ce", "--c0", "--c1", "--c2", "--c3", "--c4"]
        for req in required_vars:
            self.assertIn(req, declared_vars, f"Required CSS variable '{req}' missing from :root")

        # 2. Extract all var(--name) usages
        var_usages = set(re.findall(r'var\((--[a-zA-Z0-9_\-]+)\)', css_text))
        for usage in var_usages:
            self.assertIn(
                usage, declared_vars,
                f"Variable '{usage}' used in animation or cell rules but never defined in :root!"
            )

        # 3. Check palette values in :root: must be living systems emeralds/slate
        for var_name, color_val in declared_vars.items():
            clean_hex = color_val.lstrip("#").upper()
            if len(clean_hex) == 8: # e.g. 1b1f230a with alpha
                clean_hex = clean_hex[:6]
            self.assertNotIn(
                clean_hex, FORBIDDEN_CYAN_BLUE_HEXES,
                f"Forbidden sci-fi blue/neon hex '{color_val}' found in {var_name}"
            )

        # 4. Verify snake head is emerald #10B981
        self.assertEqual(
            declared_vars.get("--cs", "").upper(), "#10B981",
            f"Snake head --cs must be emerald #10B981, found {declared_vars.get('--cs')}"
        )

    def test_css_selector_specificity_and_scoping(self):
        """
        Verify CSS in header.svg and footer.svg does NOT use universal selectors
        or unbounded HTML element tags that could break when embedded in SVGs.
        """
        for target in [self.header_path, self.footer_path]:
            content = target.read_text(encoding="utf-8")
            style_match = re.search(r"<style>(.*?)</style>", content, re.DOTALL)
            if not style_match:
                continue
            css_text = style_match.group(1)

            # Strip comments and @keyframes blocks to inspect rule selectors
            no_keyframes = re.sub(r'@keyframes[^{]+\{(?:[^{}]*\{[^{}]*\})*[\s\n]*\}', '', css_text, flags=re.DOTALL)
            rules = re.findall(r'([^{]+)\{([^}]+)\}', no_keyframes)

            for selector, body in rules:
                selector = selector.strip()
                self.assertNotIn("*", selector, f"Forbidden universal selector '*' in {target.name}: {selector}")
                # All custom styling should be class-based or keyframes
                self.assertTrue(
                    selector.startswith(".") or selector.startswith(":"),
                    f"Unscoped rule selector in {target.name}: '{selector}' (should be class-scoped e.g. '.title-text')"
                )

    def test_keyframes_timing_and_animations_stability(self):
        """Verify animation durations, easing curves, and keyframe intervals are valid."""
        for target in [self.header_path, self.footer_path]:
            content = target.read_text(encoding="utf-8")
            keyframes = re.findall(r'@keyframes\s+([a-zA-Z0-9_\-]+)\s*\{([^}]+)\}', content)
            self.assertGreater(len(keyframes), 0, f"{target.name} should define living systems micro-animations")

            for kf_name, kf_body in keyframes:
                stops = re.findall(r'(\d+)%', kf_body)
                self.assertIn("0", stops, f"Keyframe '{kf_name}' missing 0% stop")
                self.assertIn("100", stops, f"Keyframe '{kf_name}' missing 100% stop")


# ============================================================================
# 5. GENERATOR DETERMINISM & SUITE PARITY
# ============================================================================

class TestGeneratorDeterminismAndEcosystemParity(unittest.TestCase):
    """
    Verifies deterministic generation from scripts/generate_nature_banner.py
    and complete cross-repo SVG validity.
    """

    def test_generator_deterministic_match(self):
        """Verify scripts/generate_nature_banner.py reproduces assets/header.svg byte-for-byte."""
        sys.path.insert(0, str(REPO_ROOT / "scripts"))
        import generate_nature_banner as g

        generated = g.generate_svg().strip()
        actual = (REPO_ROOT / "assets" / "header.svg").read_text(encoding="utf-8").strip()

        self.assertEqual(
            generated, actual,
            "scripts/generate_nature_banner.py does not match assets/header.svg! Generator must be deterministic."
        )

    def test_all_25_svgs_across_repo_parse(self):
        """Stress test: parse every SVG file in the repository (assets/ and profile-3d-contrib/)."""
        svg_files = list(REPO_ROOT.glob("assets/**/*.svg")) + list(REPO_ROOT.glob("profile-3d-contrib/**/*.svg"))
        self.assertGreaterEqual(len(svg_files), 25, f"Expected at least 25 SVGs, found {len(svg_files)}")

        failed_svgs = []
        for svg_path in svg_files:
            try:
                ET.parse(svg_path)
            except Exception as e:
                failed_svgs.append((svg_path.name, str(e)))

        self.assertEqual(
            len(failed_svgs), 0,
            f"The following SVGs failed XML parsing: {failed_svgs}"
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
